// src/app/core/db-schema.ts
import { DBSchema } from 'idb';

// Database schema
export interface AppDBSchema extends DBSchema {
  sentences: {
    key: number;
    value: {
      id?: number;
      text: string;
      audio: AudioBuffer;
    };
  };
  exercises: {
    key: number;
    value: {
      id?: number;
      name: string;
      sentenceIds: number[];
    };
  };
}

// Data interfaces (you can use these throughout your application)
export interface Sentence {
  id?: number; // Optional because it will be auto-generated by IndexedDB
  text: string;
  audio: AudioBuffer;
}

export interface Exercise {
  id?: number; // Optional
  name: string;
  sentenceIds: number[];
}
